# Generated by Django 4.0.4 on 2022-05-01 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
